# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  CONTRIBUTOR: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
- 'Do Not Merge'
- 'Conflicted'

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
rules:
- minApprovals:
    CONTRIBUTOR: 1