# Configuration for mergeable - https://github.com/mergeability/mergeable

version: 1
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: 'Reviewed'
        must_exclude:
          regex: 'Do Not Merge|Conflicted'